from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 794)
        font = QtGui.QFont()
        font.setItalic(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 100, 821, 531))
        self.widget.setObjectName("widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 70, 386, 376))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.ListHeroes = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.ListHeroes.setContentsMargins(0, 0, 0, 0)
        self.ListHeroes.setObjectName("ListHeroes")
        self.hero_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hero_4.sizePolicy().hasHeightForWidth())
        self.hero_4.setSizePolicy(sizePolicy)
        self.hero_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("СтенаОрех.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hero_4.setIcon(icon)
        self.hero_4.setIconSize(QtCore.QSize(112, 81))
        self.hero_4.setFlat(True)
        self.hero_4.setObjectName("hero_4")
        self.ListHeroes.addWidget(self.hero_4, 1, 0, 1, 1)
        self.hero_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hero_2.sizePolicy().hasHeightForWidth())
        self.hero_2.setSizePolicy(sizePolicy)
        self.hero_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.hero_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Патсолнух.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hero_2.setIcon(icon1)
        self.hero_2.setIconSize(QtCore.QSize(112, 81))
        self.hero_2.setFlat(True)
        self.hero_2.setObjectName("hero_2")
        self.ListHeroes.addWidget(self.hero_2, 0, 1, 1, 1)
        self.hero_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hero_5.sizePolicy().hasHeightForWidth())
        self.hero_5.setSizePolicy(sizePolicy)
        self.hero_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Морозный Горох.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hero_5.setIcon(icon2)
        self.hero_5.setIconSize(QtCore.QSize(112, 81))
        self.hero_5.setFlat(True)
        self.hero_5.setObjectName("hero_5")
        self.ListHeroes.addWidget(self.hero_5, 1, 1, 1, 1)
        self.hero_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hero_1.sizePolicy().hasHeightForWidth())
        self.hero_1.setSizePolicy(sizePolicy)
        self.hero_1.setStyleSheet("")
        self.hero_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Горохострел1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hero_1.setIcon(icon3)
        self.hero_1.setIconSize(QtCore.QSize(112, 81))
        self.hero_1.setFlat(True)
        self.hero_1.setObjectName("hero_1")
        self.ListHeroes.addWidget(self.hero_1, 0, 0, 1, 1)
        self.hero_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hero_3.sizePolicy().hasHeightForWidth())
        self.hero_3.setSizePolicy(sizePolicy)
        self.hero_3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.hero_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Вишнёвые бомбы.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hero_3.setIcon(icon4)
        self.hero_3.setIconSize(QtCore.QSize(112, 81))
        self.hero_3.setFlat(True)
        self.hero_3.setObjectName("hero_3")
        self.ListHeroes.addWidget(self.hero_3, 0, 2, 1, 1)
        self.hero_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hero_6.sizePolicy().hasHeightForWidth())
        self.hero_6.setSizePolicy(sizePolicy)
        self.hero_6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Жевун.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hero_6.setIcon(icon5)
        self.hero_6.setIconSize(QtCore.QSize(112, 81))
        self.hero_6.setFlat(True)
        self.hero_6.setObjectName("hero_6")
        self.ListHeroes.addWidget(self.hero_6, 1, 2, 1, 1)
        self.hero_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hero_8.sizePolicy().hasHeightForWidth())
        self.hero_8.setSizePolicy(sizePolicy)
        self.hero_8.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Ледогриб.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hero_8.setIcon(icon6)
        self.hero_8.setIconSize(QtCore.QSize(112, 81))
        self.hero_8.setFlat(True)
        self.hero_8.setObjectName("hero_8")
        self.ListHeroes.addWidget(self.hero_8, 2, 1, 1, 1)
        self.hero_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hero_7.sizePolicy().hasHeightForWidth())
        self.hero_7.setSizePolicy(sizePolicy)
        self.hero_7.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Гипногриб.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hero_7.setIcon(icon7)
        self.hero_7.setIconSize(QtCore.QSize(112, 81))
        self.hero_7.setFlat(True)
        self.hero_7.setObjectName("hero_7")
        self.ListHeroes.addWidget(self.hero_7, 2, 0, 1, 1)
        self.hero_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hero_9.sizePolicy().hasHeightForWidth())
        self.hero_9.setSizePolicy(sizePolicy)
        self.hero_9.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Кабачок.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hero_9.setIcon(icon8)
        self.hero_9.setIconSize(QtCore.QSize(112, 81))
        self.hero_9.setFlat(True)
        self.hero_9.setObjectName("hero_9")
        self.ListHeroes.addWidget(self.hero_9, 2, 2, 1, 1)
        self.hero_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hero_10.sizePolicy().hasHeightForWidth())
        self.hero_10.setSizePolicy(sizePolicy)
        self.hero_10.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Колючки.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hero_10.setIcon(icon9)
        self.hero_10.setIconSize(QtCore.QSize(112, 81))
        self.hero_10.setFlat(True)
        self.hero_10.setObjectName("hero_10")
        self.ListHeroes.addWidget(self.hero_10, 3, 0, 1, 1)
        self.hero_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hero_11.sizePolicy().hasHeightForWidth())
        self.hero_11.setSizePolicy(sizePolicy)
        self.hero_11.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Высокие Орехи.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hero_11.setIcon(icon10)
        self.hero_11.setIconSize(QtCore.QSize(112, 81))
        self.hero_11.setFlat(True)
        self.hero_11.setObjectName("hero_11")
        self.ListHeroes.addWidget(self.hero_11, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(85, 255, 0)")
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.closer = QtWidgets.QPushButton(self.widget)
        self.closer.setGeometry(QtCore.QRect(40, 490, 51, 31))
        self.closer.setAutoFillBackground(False)
        self.closer.setStyleSheet("font: 75 12pt \"System\";\n"
"background-color:rgb(255, 255, 255)")
        self.closer.setCheckable(False)
        self.closer.setAutoExclusive(False)
        self.closer.setAutoDefault(False)
        self.closer.setDefault(False)
        self.closer.setFlat(False)
        self.closer.setObjectName("closer")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 490, 31, 31))
        self.label_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Поставлю два и только два.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(490, 169, 301, 211))
        self.lineEdit.setObjectName("lineEdit")
        self.image_connect = QtWidgets.QLabel(self.widget)
        self.image_connect.setGeometry(QtCore.QRect(490, 29, 171, 121))
        self.image_connect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image_connect.setText("")
        self.image_connect.setObjectName("image_connect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 993, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.closer.clicked.connect(self.widget.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Информация о растениях"))
        self.closer.setText(_translate("MainWindow", "CLOSE"))
